### PR TITLE
Add reply to flag in email field plugin

### PR DESCRIPTION
**Pull request by manojiitkgp09**

### CODE REVIEW

**Comment by FinalAngel** [comment]
@czpython or @stefanfoulis would you be able to look at this PR?

**Comment by FinalAngel** [comment]
@stefanfoulis awesome, @manojiitkgp09 would you be able to add an entry to the CHANGELOG like:

```
2.3.0 (unreleased)
------------------
* change...
```

**Comment by manojiitkgp09** [comment]
@czpython Our requirement is that we want to send email to multiple staff members when some customers sign up on our website. And the recipient field is present in formplugin as seen here https://github.com/aldryn/aldryn-forms/blob/71facb1c1c87b93d261b99ca9a993775f3a14701/aldryn_forms/models.py#L163

**Comment by czpython** [comment]
@manojiitkgp09 
This is already possible with the Advanced form. I suggest to create an advanced form, configure it and just move all fields from the normal form to the advanced one.

Using the recipients field in the normal form is discouraged and will be deprecated.
The advanced form solves the same problem in a more efficient and flexible way.

**Pull request closed without merging**
